#!/usr/bin/env python3
"""Transplant results figure: before/after text comparison.

Shows pure author vs transplanted output for the three best pairs,
with PPL numbers. Designed to be readable at LinkedIn scale.

Usage:
    python scripts/fig_transplant.py
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

FIGURES_DIR = Path("figures")
TRANSPLANT_JSON = Path("outputs/transplant_samples.json")


def load_pairs():
    """Load transplant data from JSON (generated by generate_samples flow)."""
    with open(TRANSPLANT_JSON) as f:
        data = json.load(f)

    prompt = data["prompt"]
    pairs = []
    for host, info in data["pairs"].items():
        pairs.append({
            "host": host.capitalize() if host != "minimalist" else "Minimalist*",
            "donor": data["donor"].capitalize(),
            "host_ppl": info["pure_ppl"],
            "transplant_ppl": info["transplant_ppl"],
            "pure": info["pure_text"],
            "transplanted": info["transplant_text"],
        })
    return prompt, pairs


def wrap_text(text, width=48):
    """Hard-wrap text so matplotlib doesn't overflow boxes."""
    import textwrap
    return textwrap.fill(text, width=width)


def main():
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    prompt, PAIRS = load_pairs()

    # Compute row heights based on text length
    wrap_w = 48
    row_heights = []
    for pair in PAIRS:
        lines_l = wrap_text(pair["pure"], wrap_w).count("\n") + 1
        lines_r = wrap_text(pair["transplanted"], wrap_w).count("\n") + 1
        n_lines = max(lines_l, lines_r)
        # title line + label + text lines, with some padding
        row_heights.append(max(n_lines * 0.32 + 1.2, 1.8))

    fig, axes = plt.subplots(
        len(PAIRS), 1, figsize=(14, sum(row_heights) + 1.5),
        gridspec_kw={"height_ratios": row_heights},
    )
    if len(PAIRS) == 1:
        axes = [axes]

    for ax, pair, rh in zip(axes, PAIRS, row_heights):
        ax.set_xlim(0, 12)
        ax.set_ylim(0, rh)
        ax.axis("off")

        host = pair["host"]
        donor = pair["donor"]
        box_h = rh - 0.55  # leave space for title above boxes
        box_bot = 0.1

        # Title bar
        ax.text(0.0, rh - 0.05, f"{host} + {donor}'s H14",
                fontsize=13, fontweight="bold", va="top",
                fontfamily="monospace")
        ax.text(12.0, rh - 0.05,
                f"PPL: {pair['host_ppl']:.0f} → {pair['transplant_ppl']:.0f}",
                fontsize=11, fontweight="bold", va="top", ha="right",
                color="#C44E52")

        # Pure output box
        ax.add_patch(mpatches.FancyBboxPatch(
            (0, box_bot), 5.2, box_h, boxstyle="round,pad=0.12",
            facecolor="#f0f0f0", edgecolor="#cccccc", linewidth=1))
        text_top = box_bot + box_h - 0.15
        ax.text(0.2, text_top, f"Pure {host}:", fontsize=9.5,
                fontweight="bold", va="top", color="#555555")
        ax.text(0.2, text_top - 0.35, wrap_text(pair["pure"], wrap_w),
                fontsize=9, va="top", fontfamily="serif", style="italic",
                color="#333333", linespacing=1.3)

        # Arrow
        mid_y = box_bot + box_h / 2
        ax.annotate("", xy=(6.3, mid_y), xytext=(5.55, mid_y),
                    arrowprops=dict(arrowstyle="->", color="#C44E52",
                                    lw=2.5))
        ax.text(5.92, mid_y - 0.25, f"+H14\nfrom\n{donor}",
                fontsize=7.5, ha="center", va="top", color="#C44E52",
                fontweight="bold")

        # Transplanted output box
        ax.add_patch(mpatches.FancyBboxPatch(
            (6.6, box_bot), 5.3, box_h, boxstyle="round,pad=0.12",
            facecolor="#fff5f5", edgecolor="#C44E52", linewidth=1.5))
        ax.text(6.8, text_top, f"{host} + {donor}'s H14:",
                fontsize=9.5, fontweight="bold", va="top", color="#C44E52")
        ax.text(6.8, text_top - 0.35, wrap_text(pair["transplanted"], wrap_w),
                fontsize=9, va="top", fontfamily="serif", style="italic",
                color="#333333", linespacing=1.3)

    fig.suptitle('Head transplant: grafting Poe\'s H14 into other authors\n'
                 f'Prompt: "{prompt}" (seed=42)',
                 fontsize=14, fontweight="bold", y=0.99)

    plt.tight_layout(rect=[0, 0, 1, 0.92])
    plt.savefig(FIGURES_DIR / "transplant.png", dpi=150, bbox_inches="tight")
    print(f"Saved {FIGURES_DIR / 'transplant.png'}")
    plt.close()


if __name__ == "__main__":
    main()